// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/webook-project-go/webook-active/grpc"
	"github.com/webook-project-go/webook-active/ioc"
	"github.com/webook-project-go/webook-active/repository/redis"
	"github.com/webook-project-go/webook-active/service"
)

// Injectors from wire.go:

func InitApp() *App {
	client := ioc.InitEtcd()
	grpcxServer := ioc.InitGrpcServer(client)
	cmdable := ioc.InitRedis()
	redisClient := redis.New(cmdable)
	serviceService := service.New(redisClient)
	grpcService := grpc.New(serviceService)
	saramaClient := ioc.InitKafka()
	logger := ioc.InitLogger()
	v := ioc.InitConsumer(saramaClient, logger, serviceService)
	app := &App{
		Server:    grpcxServer,
		Service:   grpcService,
		Consumers: v,
	}
	return app
}

// wire.go:

var activeServiceProvider = wire.NewSet(service.New, redis.New)

var thirdPartyProvider = wire.NewSet(ioc.InitRedis, ioc.InitKafka, ioc.InitLogger, ioc.InitEtcd)
